apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer-ridethenet"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - webapp-1.apps.ridethenet.be
    secretName: tls-cert-from-certman
  rules:
  - host: webapp-1.apps.ridethenet.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app
            port:
              number: 80
